### ISSUE TITLE
Installation uninstalls Django current version

### ISSUE THREAD

**Issue by RicardoFernandez-UY** [keycloak-client/keycloak-client#11]
When installing the library according to the instructions it uninstalls my django 4.1 and instead installs version 3.2.15.
Is it possible to use the library with Djanjo 4.x?

Thank you

**Comment by akhilputhiry** [comment]
I believe you must be using  `pip install "keycloak[extensions]"` 
just install the normal version and django seperate `pip install keycloak django==x.x.x.`
