### ISSUE TITLE
Support for policy enforcer

### ISSUE THREAD

**Issue by akhilputhiry** [keycloak-client/keycloak-client#42]

**Comment by mikesmith1611** [comment]
Any progress on this? If not how can I manually check a user is authorized to access and endpoint using policies set up in keycloak?

**Comment by akhilputhiry** [comment]
@mikesmith1611 Everything needed to implement policy enforcer is already present inside the `access_token`. Access token contains a field called `authorization` which tells us what all resources does the user has access to based on the policies configured within the keycloak server. We just need to lookup the values and block the connection.

```
{
  "jti": "3e878cd7-b66d-428b-b44e-9a4d61870650",
  "exp": 1572246557,
  "nbf": 0,
  "iat": 1572246497,
  "iss": "https://keycloak.akhilputhiry.dev/auth/realms/master",
  "aud": [
    "python-client",
    "account"
  ],
  "sub": "e1fbd7d6-ad2b-407f-89cf-6c2b004d78bb",
  "typ": "Bearer",
  "azp": "python-client",
  "auth_time": 0,
  "session_state": "bec74b80-602e-43e9-b0e1-ca49c05ab48e",
  "acr": "1",
  "realm_access": {
    "roles": [
      "offline_access",
      "uma_authorization"
    ]
  },
  "resource_access": {
    "python-client": {
      "roles": [
        "uma_protection"
      ]
    },
    "account": {
      "roles": [
        "manage-account",
        "manage-account-links",
        "view-profile"
      ]
    }
  },
  "authorization": {
    "permissions": [
      {
        "rsid": "bb6a777f-a17b-4555-b035-a6ce12a1fd21",
        "rsname": "Default Resource"
      }
    ]
  },
  "scope": "email profile",
  "clientHost": "180.151.137.140",
  "clientId": "python-client",
  "email_verified": false,
  "preferred_username": "service-account-python-client",
  "clientAddress": "180.151.137.140",
  "email": "service-account-python-client@placeholder.org"
}
```

**Comment by juliohm1978** [comment]
I'm trying to get this to work, but the access token sent to my resource server does not have the `autorization.permissions[]` list.

```
    kc = Client()
    token = kc.decode(kc.access_token)
    print(token)
```

Am I doing something wrong here?

**Comment by akhilputhiry** [comment]
Hi @juliohm1978 
Thank you for trying out `keyclock-client`
Few things I would like to get clarification

* Do you have any users configured in your keycloak server ?
* Have you configured the Permissions (Authorization => Permissions) in your keycloak server

```
kc = Client()  # this uses client credentials present in keycloak.json
kc = Client(username='myuser', password='*****')  # use this method for testing against a user
```

Permissions are only applicable for users not the clients. You can also verify the same from the `Evaluate` tab under `Authorization`


<img width="1670" alt="Screenshot 2020-08-03 at 7 49 48 AM" src="https://user-images.githubusercontent.com/747410/89140301-dd05ac00-d55e-11ea-9c30-ea437af32d30.png">

**Comment by juliohm1978** [comment]
Hi @akhilputhiry,

Apologies for not giving more details at first hand.

1) I have users configuered in the Keycloak server. They are federated to a corporate Active Directory. They can successfully login into my Django application using Keycloak.

2) Authorization and Permissions are configured. I'm only begining to test, so my client has only one policy that allows my user to any resources.

![image](https://user-images.githubusercontent.com/4145456/89141046-ca1cb880-d519-11ea-9be4-03026e21a48d.png)

With an authenticated user, I'm testing the code below inside my Django application.

```python
    kc = Client()
    token = kc.decode(kc.access_token)
    print(token)
```

This is done inside a view I want to protect with Keycloak Authorization policies. I will manage to create more policies with specific rules, but at the moment, I don't understand how to decode the access token correctly, or which token I should be using here.

The above shows the access token sent by the user's browser, when it issues an authenticated GET request to my Django view.

But the contents of the token does not have the list of authorized resources. This is really confusing.

**Comment by juliohm1978** [comment]
The token is actually similar to the one I get from Keycloak itself, when evaluating the Client Scope.

![image](https://user-images.githubusercontent.com/4145456/89141608-68f5e480-d51b-11ea-8389-71e36085ddaf.png)

```
{
  "exp": 1596423460,
  "iat": 1596423160,
  "jti": "a809dbda-e296-418a-b273-18075e622104",
  "iss": "https://sso.dev.tjpr.jus.br/auth/realms/development",
  "aud": "account",
  "sub": "229e690f-7305-4d4e-9a60-459c155f8773",
  "typ": "Bearer",
  "azp": "django-app",
  "session_state": "1a40850b-cf02-4f4d-86fc-d20a2bd71d73",
  "acr": "1",
  "allowed-origins": [
    "http://127.0.0.1:8000"
  ],
  "realm_access": {
    "roles": [
      "offline_access",
      "uma_authorization"
    ]
  },
  "resource_access": {
    "account": {
      "roles": [
        "manage-account",
        "manage-account-links",
        "view-profile"
      ]
    }
  },
  "scope": "openid profile microprofile-jwt email",
  "upn": "jhem",
  "email_verified": false,
  "name": "Julio Henrique Morimoto",
  "groups": [
    "offline_access",
    "uma_authorization"
  ],
  "preferred_username": "jhem",
  "locale": "pt-BR",
  "given_name": "Julio Henrique",
  "family_name": "Morimoto",
  "email": "jhem@tjpr.jus.br"
}
```

So, my real question here, I guess, is how can I get that list of authorized resources into my access token?

**Comment by akhilputhiry** [comment]
Hi @juliohm1978 

I had to make a small patch to get the permissions working.
You can see the changes [here](https://github.com/chunky-monkeys/keycloak-client/pull/51/files).

I have made a release candidate with the patch required for RPT to work properly called `3.0.1rc1`
Could you please try installing `pip install keycloak==3.0.1rc1` and see whether its working for you or not

```
# example

>>>
>>> form keycloak import Client
>>> kc = Client(username='myuser', password='*****')
>>> kc.rpt(kc.access_token)
2020-08-03 11:47:54,568 [DEBUG] Retrieving RPT from keycloak
2020-08-03 11:47:54,581 [DEBUG] RPT retrieved successfully
2020-08-03 11:47:54,581 [DEBUG] Retrieving JWKs from keycloak server
2020-08-03 11:47:54,587 [DEBUG] JWKs retrieved successfully
{'exp': 1596435534, 'iat': 1596435474, 'jti': '822c7f6f-cd0a-4b9d-b55c-72803755ca7c', 'iss': 'http://localhost:8080/auth/realms/master', 'aud': ['kc', 'account'], 'sub': 'fce7f440-2e40-4161-90b4-61a1913c4b28', 'typ': 'Bearer', 'azp': 'kc', 'session_state': 'b3498962-3973-4f2d-9150-b1338e974d08', 'acr': '1', 'realm_access': {'roles': ['offline_access', 'uma_authorization']}, 'resource_access': {'account': {'roles': ['manage-account', 'manage-account-links', 'view-profile']}}, 'authorization': {'permissions': [{'rsid': '992dfa45-6098-45ac-b62e-da4d2787377f', 'rsname': 'Default Resource'}]}, 'scope': 'profile email', 'email_verified': True, 'preferred_username': 'akhilputhiry'}
>>>
```

**Comment by juliohm1978** [comment]
I was able to get it working. Turns out, I was decoding the wrong access token. The following code decodes the client token, not the user token.

```python
kc = Client()
token = kc.decode(kc.access_token)
print(token)
```

In fact, I need to acquire a new RPT token created from the user's access token stored in session after authentication.

```python
rpt_token = self.kc.rpt(request.session["tokens"]["access_token"])
decoded_token = self.kc.decode(rpt_token)
print(token)
```

The RPT token is the one that actually has an authorization/permission list.

For reference: https://www.keycloak.org/docs/latest/authorization_services/#_service_user_managed_access

All that in context, I have to agree with the original issue request.

The library is missing a formal implementation of the PEP (Policy Enforcement Point). The RPT token provides a full list of resources the user has access to, but that code snippet is only part of a full PEP. You can save a snapshot in session, and use it to enforce policies, but it lacks more elaborate features, like refreshing expired tokens. If you need to refresh permissions, you need to refresh the RPT every 5 minutes (whatever your client configuration is on Keycloak).

I believe this can be done in the provided middleware. I'll be glad to push a PR in the future if I ever get the chance to share my implementation.

Thank you for the help!
