### ISSUE TITLE
python >= 3.7 requirement?

### ISSUE THREAD

**Issue by egamberini** [keycloak-client/keycloak-client#6]
Hi!
I would like to ask what's the reason for this requirement:
https://github.com/keycloak-client/keycloak-client/blob/aed737ec42c2e01abf364563d7796e0c647ee09a/pyproject.toml#L8

The library in version 3.1.3 seems to work fine for me on python 3.6 after `make install`ing `keycloak` but probably I missed some test case.

I'm asking since an existing python 3.6 project of mine is/was using `keycloak==3.0.2`, which is not available anymore on https://pypi.org/project/keycloak/ and `pip3.6` :(

Thank you!

**Comment by cute-as-ducks** [comment]
I am are really sorry for the late reply @egamberini 
I believe you must have figured a way out, if not we can surely try to include 3.6

**Comment by egamberini** [comment]
Hi @cute-as-ducks , no problem, indeed we moved the project to a newer python version
