### ISSUE TITLE
Redirect is not allowed for a preflight request

### ISSUE THREAD

**Issue by dennisjunior111** [keycloak-client/keycloak-client#71]
I followed the flask example as a starting point: https://github.com/keycloak-client/keycloak-client/blob/main/examples/flask/app.py. 

The middleware seems to work as expected when accessing the API endpoints directly. However, when I make a non-simple request to the API from a frontend application, the client calls for a preflight OPTIONS request. The middleware attempts to redirect the request to keycloak, but redirections in preflight requests are not allowed. As such, the request fails not because the actual request would fail if executed, but because the client is unable to complete the OPTIONS preflight request.

Is there a way to utilize the middleware, but disable all OPTIONS requests from being re-routed to keycloak so preflight requests can be returned by the API itself?

`Access to XMLHttpRequest at 'http://localhost:5000/people?name=john' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.`

**Comment by akhilputhiry** [comment]
Hi @dennisjunior111 

Thanks for reaching out to us. 

If I understand it correctly, you have a frontend application and a backend application and while making api calls from your frontend application you are hitting the CORS problem. 

from the message you posted I could see that your frontend application is running on port `3000` and backend is running on port `5000` which is causing the CORS issue. 

There are multiple solutions to this problem. 

* Proxy the apis to the backend application using [webpack devserver](https://webpack.js.org/configuration/dev-server/#devserverproxy) ( this is a standard practise )
* You can enable CORS headers in the backend using plugins like [Flask-CORS](https://flask-cors.readthedocs.io/en/latest/)

This client has nothing to do with the CORS issue. Its a security feature implemented inside the browsers. You can read about it more [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS)

Thanks
